import { getHomeProjectsDetails, projectDetailsInterface } from "@/lib/projects"
import Head from "next/head"
import Image from "next/image"
import router from "next/router"
import { useEffect, useState } from "react"
import { adjectives } from "@/lib/adjectives"


export default function Home() {
	const [projectsData, setProjectData] = useState([])

	useEffect(() => {
		const projectDetails: projectDetailsInterface[] = getHomeProjectsDetails()
		setProjectData(projectDetails)
	}, [])

	const [currentAdjective, setCurrentAdjective] = useState(adjectives[0])

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-col">
				<div className="px-4 xl:px-96">
					<div>
						<h1 className="text-5xl font-bold mb-5">
							Caroline <span className="text-red-500">♦️</span>
						</h1>
						<ul className="flex overflow-auto">
							{adjectives.map(adjective => (
								<li key={adjective.id}
									role="button"
									className={`
										mr-8
										flex
										flex-col
										items-center
										${adjective.id === currentAdjective.id ?
									"text-white" : "text-dark-blue-light"}
									`}
									onClick={() => {
										setCurrentAdjective(adjective)
										const newActiveAdjective = document.getElementById(adjective.id)
										if (newActiveAdjective) newActiveAdjective.scrollIntoView({ behavior: "smooth" })

									}}>
									<span className={currentAdjective.id === adjective.id ? "font-bold" : ""}>
										{adjective.title}
									</span>
									{adjective.id === currentAdjective.id ? (
										<span className="w-2 h-2 bg-white block rounded-full" />
									) : null}
								</li>
							))}
						</ul>
						<ul className="mt-4 flex overflow-auto min-h-[25rem] snap-x items-center lg:flex-wrap">
							{adjectives.map(adjective => (
								<li key={adjective.id}
									id={adjective.id}
									className={`
										relative
										mx-4
										lg:my-8
										bg-slate-400
										rounded-[20px]
										transition
										ease-in-out
										h-[22rem] min-w-[18rem]
										${adjective.id === currentAdjective.id ?
									"scale-110 duration-300"
									: ""}
									`}
									style={{
										backgroundImage: `url(${adjective.image.src})`,
										backgroundRepeat: "no-repeat",
										backgroundSize: "cover",
										backgroundPosition: "center"
									}}

								>
									<div
										className={`
											absolute
											top-0
											left-0
											bg-gradient-to-b
											from-transparent
											to-slate-900/70
											rounded-[20px]
											transition
											ease-in-out
											h-[22rem] min-w-[18rem]
											snap-center
											p-4
											flex
											flex-col
											justify-end
											${adjective.id === currentAdjective.id ?
									"scale-100 duration-300"
									: ""}
									`}
									>
										<p className="font-bold">{adjective.title}</p>
										<p>{adjective.text}</p>
									</div>
								</li>
							))}
						</ul>
					</div>
					<div className="mb-5 mt-14">
						<div className="flex justify-between items-center mb-5">
							<h2 className="text-3xl font-bold">
								Projets
							</h2>
							<button
								className="text-dark-blue-light"
								onClick={() => {
									router.push("projects")
								}}>Voir plus</button>
						</div>
						{projectsData ? (
							<ul className="flex overflow-auto snap-x">
								{projectsData.map((project: projectDetailsInterface) => (
									<li
										key={project.title}
										role="button"
										className="flex flex-col items-center mr-6 w-[6rem]"
										onClick={() => {
											router.push(`projects/${project.link}`)
										}}
									>
										<div
											className="
												min-h-[6rem]
												min-w-[6rem]
												bg-white
												rounded-full
												flex
												justify-center
												items-center
												snap-center
											">
											<Image
												src={project.icon}
												alt={project.title}
												width={60}
												height={80}
											/>
										</div>
										<h3 className="text-center">{project.title}</h3>
									</li>
								))}

							</ul>
						) : null}
					</div>
				</div>
			</main>
		</>
	)
}
